version: "3"
services:
  backend:
    container_name: "backend"
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - type: bind
        source: ../django_docker/
        target: /app
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    container_name: "db"
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure


  redis:
    container_name: "redis"
    image: redis:latest
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data


volumes:
  pg_data:
  redis_data:


networks:
  backend:
    driver: bridge
