name: "Build and Deploy"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Apply migration
        run: python manage.py migrate --settings=django_ci_cd.settings.test
      - name: Run tests
        run: python manage.py test --settings=django_ci_cd.settings.test
