name: "Build and Deploy"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Apply migration
        run: python manage.py migrate --settings=django_ci_cd.settings.test
      - name: Run tests
        run: python manage.py test --settings=django_ci_cd.settings.test



  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Building...
        run: echo "building image..."
      - name: Checkout
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
      - name: Install dependencies
        run: pip install -r requirements.txt


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy...
        run: echo "Deploy..."
      - name: Checkout
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
